rules = [
  OrganizeImports,
  NoAutoTupling,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  RedundantSyntax
]

OrganizeImports {
  groupedImports = Keep
  groups = ["re:java?\\.", "scala.", "*"]
  removeUnused = false
}