version = 3.7.14
runner.dialect = scala212
style = defaultWithAlign
maxColumn = 140
project {
  git = true
}

rewrite {
  trailingCommas.style = never
}

fileOverride {
  "glob:**/project/**" {
    runner.dialect = scala212
  }
  "glob:*.sbt" {
    runner.dialect = scala212
  }
}

docstrings.style = Asterisk
docstrings.wrap = no